<a href="https://colab.research.google.com/github/Angela-Benedict/ds2002-fa26/blob/main/Copy_of_Benedict_2026_10_28_%E2%80%94_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Midterm Checkpoint

**Lab — 2026-10-23 · Fall 2026**  

---

## Lab 09 — Midterm checkpoint, week 1 of 3

**What you submit: the link to your team's main repo. Only that.** One submission per team. Do not upload separate files.

Put this notebook in the repo (the `notebooks/` folder is fine) and push it, so everything we check is in one place.

**You do not have to fill this all out.** It is a checkpoint, not a finished project. Skip any section you have not started and write "not started" next to it. What we must see is:

1. **Your charter**, committed to the repo
2. **Any progress** you have made, with code that ran and output you can point at

Start with the team setup, then work down the same eight things we listed at Monday's kickoff, as far as you have gotten. This is graded on evidence, not on intentions.

The purpose is to catch a stalled team while there is still time to unstall it. If something is not working, say so here plainly. A checkpoint that honestly reports "the API join is not working and here is the error" is worth more than one that claims progress that does not exist, and it gets you help on Monday.

### Team setup

This part is required. Fill it in once for the whole team.

You need:

- Your team name, and every member with a GitHub handle (2 to 4 people)
- A link to your team's **main repo**. This is the one link you submit.
- A link to `CHARTER.md` in that repo, the page on GitHub, not a file on someone's laptop

Nice to have, and also in your charter: this week's notebook owner, your meeting time, and the five worst problems in the data from the profile you ran on Monday. Be specific: "`unit_price` is stored as text and some values start with `$`" beats "prices are messy."

In [1]:
team_setup = {
    'team_name': 'Salt Squared',
    'members': [                                  # everyone on the team, 2 to 4 people
        {'name': 'Aubin Barcheck', 'github': 'AubinB264'},
        {'name': 'Noor Imat', 'github': 'noorimat'},{'name': 'Angela Benedict', 'github': 'Angela-Benedict'},
        {'name': 'Nico Roppatte', 'github': 'Nicoroppatte'}
    ],
    'repo_url': 'https://github.com/Angela-Benedict/ds2002-fa26/tree/main/notebooks/walmart-hurricane-project',                           # your main team repo: https://github.com/...
    'charter_url': 'https://github.com/Angela-Benedict/ds2002-fa26/blob/main/notebooks/walmart-hurricane-project/CHARTER.md',                        # link to CHARTER.md in that repo
    'notebook_owner_this_week': 'TODO',           # nice to have
    'meeting_time': 'TODO',                       # nice to have, e.g. 'Tue and Thu 7pm'
    'five_worst_problems': ['TODO'],              # nice to have, five specific problems
}

def check_team(t, quiet=False):
    def real(v):
        return isinstance(v, str) and v.strip() != '' and not v.startswith('TODO')
    required = {
        'team name': real(t['team_name']),
        '2 to 4 members, each with a name and GitHub handle':
            2 <= len(t['members']) <= 4 and all(real(m['name']) and real(m['github']) for m in t['members']),
        'main repo link': real(t['repo_url']) and t['repo_url'].startswith('https://github.com/'),
        'charter link points at CHARTER.md': real(t['charter_url']) and t['charter_url'].endswith('CHARTER.md'),
    }
    nice = {
        'notebook owner': real(t['notebook_owner_this_week']),
        'meeting time': real(t['meeting_time']),
        'five specific problems': len(t['five_worst_problems']) >= 5 and all(real(p) for p in t['five_worst_problems']),
    }
    if not quiet:
        print('REQUIRED')
        for label, good in required.items():
            print('  PASS' if good else '  FAIL', '-', label)
        print('NICE TO HAVE')
        for label, good in nice.items():
            print('  done' if good else '  not yet', '-', label)
        print()
        print('team setup complete:', all(required.values()))
    return all(required.values())

check_team(team_setup)

REQUIRED
  PASS - team name
  PASS - 2 to 4 members, each with a name and GitHub handle
  PASS - main repo link
  PASS - charter link points at CHARTER.md
NICE TO HAVE
  not yet - notebook owner
  not yet - meeting time
  not yet - five specific problems

team setup complete: True

True

In [2]:
!rm -rf /content/ds2002-fa26
!git clone https://github.com/Angela-Benedict/ds2002-fa26.git /content/ds2002-fa26

Cloning into '/content/ds2002-fa26'...
remote: Enumerating objects: 341, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 341 (delta 51), reused 0 (delta 0), pack-reused 241 (from 1)
Receiving objects: 100% (341/341), 1.16 MiB | 9.79 MiB/s, done.
Resolving deltas: 100% (129/129), done.

Now show that the charter is actually committed. This is required. Run the next cell and leave its output in the notebook. Point `REPO_PATH` at your local clone of the team repo. If it prints a line like `a1b2c3d Add team charter`, you are done. If it prints "no commits found," the charter is not in the repo yet, so commit it and push before you submit.

In [3]:
import subprocess

REPO_PATH = '/content/ds2002-fa26'      # your local clone of the team repo

result = subprocess.run(['git', '-C', REPO_PATH, 'log', '--oneline', '--', 'notebooks/walmart-hurricane-project/CHARTER.md'],
                        capture_output=True, text=True)
print(result.stdout.strip() or 'no commits found for CHARTER.md')

cead256 Finalize team roles and project goals in CHARTER.md
be761ee Aubin's Changes
ce8df94 Update CHARTER.md - Nico
2901d19 Update meeting time to TBD in CHARTER.md
c48268a Update time limits description in CHARTER.md
a08d2d8 Update team goals and notebook ownership details
935cf01 Revise roles and question ownership in CHARTER.md
04fed2b Update backup owner for analysis Q1-Q5
8a4fba2 Update owner for analysis Q1-Q5 in CHARTER.md
23cb1d0 Update backup owner for cleaning decision log
0155314 fix
9d95a8d Update repo URL in CHARTER.md
bc424ed Update roles and responsibilities in CHARTER.md
090a576 Create team charter for Walmart hurricane project
416d7cb Create CHARTER.md

### 1 — Your cleaning pipeline as functions

**TODO:** paste the cleaning code you have written so far. It should be functions, not loose cells, and it should cover at minimum: duplicates, `unit_price` to numeric (it comes in as text, some with a `$`), the negative `quantity` values with your decision applied, `timestamp` parsed, and `store_id` cleaned up so it will join to the store file.

Print the row count before and after. We want to see how many rows your decisions removed.

In [4]:
import pandas as pd

distribution = pd.read_csv("https://raw.githubusercontent.com/Angela-Benedict/ds2002-fa26/refs/heads/main/notebooks/walmart-hurricane-project/data/distribution_centers.csv")

distribution['surge_capacity'] = distribution['surge_capacity'].str.replace('~', '', regex=False).astype(int)
distribution

,dc_id,dc_name,city,state,avg_daily_shipments,surge_capacity,distance_to_orlando_mi,cost_per_shipment
0,DC-JAX,Jacksonville Distribution Center,Jacksonville,FL,500,1000,141,245.0
1,DC-ATL,Atlanta Distribution Center,Atlanta,GA,400,700,438,412.5
2,DC-DAL,Dallas Distribution Center,Dallas,TX,300,600,1108,687.0
3,DC-MIA,Miami Distribution Center,Miami,FL,350,750,235,298.0
4,DC-BHM,Birmingham Distribution Center,Birmingham,AL,250,500,503,NaN

In [29]:
import pandas as pd
import string

products = pd.read_csv("https://raw.githubusercontent.com/Angela-Benedict/ds2002-fa26/refs/heads/main/notebooks/walmart-hurricane-project/data/product_catalog.csv")

#start normalizing / cleaning product_name column?

#I honestly don't understand any of this code...its just from the lab from last week so i copied it here and it did stuff, but it didn't fully clean the product_name column, so I'd appreciate help here.
def normalize_product_name(name):
    if pd.isna(name):
        return None

    name = name.lower().translate(
        str.maketrans("", "", string.punctuation)
    )

    words = name.split()
    words = ["poptarts" if word == "poptart" else word for word in words]

    return " ".join(sorted(words))

products['normalized_name'] = products['product_name'].apply(normalize_product_name)

products_clean = products.dropna(subset=['normalized_name', 'sku']).copy()

products_clean['sku_counts'] = (
    products_clean.groupby('normalized_name')['sku']
    .transform('nunique')
)

candidate_list = (
    products_clean[products_clean['sku_counts'] > 1]
    .sort_values('normalized_name')
)

#Check:
print(candidate_list[['sku', 'product_name', 'normalized_name', 'sku_counts']])

#should I replace product_name column with the normalized_name column? Still have more to clean in the column.
#maybe remove subcategory column?

#normalize category column:

products_clean['category'] = (
    products_clean['category']
    .str.strip()
    .str.lower()
)

category_mapping = {
    'breakfast foods': 'Breakfast',
    'breakfast': 'Breakfast',
    'emergency supplies': 'Emergency Supplies',
    'emergency': 'Emergency Supplies',
    'alcoholic beverages': 'Alcohol',
    'alcohol': 'Alcohol',
    'entertainment': 'Entertainment',
    'electronics': 'Electronics',
    'grocery': 'Grocery',
    'groceries': 'Grocery',
    'baby products': 'Baby Products',
    'baby': 'Baby Products',
    'snacks': 'Snacks',
    'health': 'Health',
    'household': 'Household'
}

products_clean['normalized_category'] = (
    products_clean['category']
    .map(category_mapping)
    .fillna(products_clean['category'].str.title())
)

#Check:
print(products_clean['normalized_category'].value_counts())

#Fix SKUs column (bring SKU stuff up here??)
#Decide what to do with missing unit_cost values.

#normalize package_size column:

products_clean['normalized_package_size'] = (
    products_clean['package_size']
    .str.lower()
    .str.strip()
    .replace({
        '4pk': '4-pack',
        '4 pack': '4-pack',
        '6 pack': '6-pack',
        '6-pack': '6-pack',
        '24 pack': '24-pack',
        '24-pack': '24-pack',
        '1 pack': 'single',
        '1-pack': 'single',
        '1pk': 'single',
        '12 pack': '12-pack',
        '12-pack': '12-pack',
        '24pk': '24-pack'
    })
)

display(products_clean[['package_size', 'normalized_package_size']])

#Need to figure out what to do about 'bundle' because references either a 24 pack of beer or an unspecified amount of peanut butter. Also, do we like keeping 'single'?

# keep original columns for comparison/validation
# products_clean = products_clean.drop(columns=['product_name'])
# products_clean = products_clean.drop(columns=['category'])
# products_clean = products_clean.drop(columns=['package_size'])

products_clean

              sku           product_name      normalized_name  sku_counts
13       LTBEER24   Light Beer (24-pack)    24pack beer light           2
12        BEER-24   Light Beer (24-pack)    24pack beer light           2
8         BAT-AA4    AA Batteries 4-Pack   4pack aa batteries           2
9     BATT_AA_4PK    AA Batteries 4-Pack   4pack aa batteries           2
16      GAME-MONO  Board Game - Monopoly  board game monopoly           3
15    MONOPOLY-01    Monopoly Board Game  board game monopoly           3
14        BG-MONO    Monopoly Board Game  board game monopoly           3
23       BREAD-WH            WHITE BREAD          bread white           2
24     WHITEBREAD            WHITE BREAD          bread white           2
25          PB-16          PEANUT BUTTER        butter peanut           2
26     PNUTBTR-16          Peanut Butter        butter peanut           2
27        CNDL-EM    Candles (Emergency)    candles emergency           2
28    CANDLE-EMRG      Emergency Candles    candles emergency           2
21       SOUP-CAN          Soup - Canned          canned soup           2
22      CNSOUP-01            Canned Soup          canned soup           2
17       CARDS-01          Playing Cards        cards playing           2
18   PLAYCARD-STD          PLAYING CARDS        cards playing           2
33       CHIPS-VP   Variety Pack - Chips   chips pack variety           2
34    CHIPVARIETY     Chips Variety Pack   chips pack variety           2
44      HDTARP-01      TARP - HEAVY DUTY      duty heavy tarp           2
43        TARP-HD        Heavy Duty Tarp      duty heavy tarp           2
11      LED-FLASH         FLASHLIGHT LED       flashlight led           2
10       FLASH-01         FLASHLIGHT LED       flashlight led           2
35       PTOWEL-6           Paper Towels         paper towels           2
36    PAPERTOWEL6           Paper Towels         paper towels           2
3   PT_STRAWBERRY   pop-tarts strawberry  poptarts strawberry           4
2   POPTART-STRAW   Pop-Tarts Strawberry  poptarts strawberry           4
1      SKU#459812    Strawberry Pop-Tart  poptarts strawberry           4
0           PT-12   pop-tarts strawberry  poptarts strawberry           4
normalized_category
Emergency Supplies    12
Grocery                6
Entertainment          5
Breakfast              4
Electronics            4
Baby Products          4
Household              4
Alcohol                2
Snacks                 2
Health                 2
Name: count, dtype: int64

   package_size normalized_package_size
0        4-pack                  4-pack
1           4pk                  4-pack
2        6 pack                  6-pack
3        4 pack                  4-pack
4        1 pack                  single
5       24 pack                 24-pack
6        1 pack                  single
7        6 pack                  6-pack
8           4pk                  4-pack
9       24 pack                 24-pack
10       6-pack                  6-pack
11       single                  single
12       bundle                  bundle
13       bundle                  bundle
14          1pk                  single
15      24-pack                 24-pack
16          1pk                  single
17          4pk                  4-pack
18      24-pack                 24-pack
19      12 pack                 12-pack
20      12 pack                 12-pack
21       single                  single
22       single                  single
23      24-pack                 24-pack
24      24 pack                 24-pack
25       bundle                  bundle
26       1-pack                  single
27       1 pack                  single
28         24pk                 24-pack
29       4 pack                  4-pack
30       4 pack                  4-pack
31       single                  single
32      12 pack                 12-pack
33       single                  single
34       4-pack                  4-pack
35       4 pack                  4-pack
36      12-pack                 12-pack
37       1 pack                  single
38      24-pack                 24-pack
39       single                  single
40       6 pack                  6-pack
41       4-pack                  4-pack
42       6 pack                  6-pack
43      12 pack                 12-pack
44         24pk                 24-pack

,sku,product_name,category,subcategory,unit_cost,supplier,package_size,normalized_name,sku_counts,normalized_category,normalized_package_size
0,PT-12,pop-tarts strawberry,breakfast foods,NaN,1.93,Johnson & Johnson,4-pack,poptarts strawberry,4,Breakfast,4-pack
1,SKU#459812,Strawberry Pop-Tart,breakfast,Pop-Tarts,2.26,Roku Inc,4pk,poptarts strawberry,4,Breakfast,4-pack
2,POPTART-STRAW,Pop-Tarts Strawberry,breakfast,NaN,2.11,Sara Lee,6 pack,poptarts strawberry,4,Breakfast,6-pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack,poptarts strawberry,4,Breakfast,4-pack
4,WTR-24,BOTTLED WATER 24PK,emergency supplies,Bottled,2.64,Sara Lee,1 pack,24pk bottled water,1,Emergency Supplies,single
5,WATER24PK,Bottled Water 24-Pack,emergency,Bottled,2.38,Sara Lee,24 pack,24pack bottled water,1,Emergency Supplies,24-pack
6,WTR_24PK,Water - 24 Pack,emergency,NaN,2.08,Frito-Lay,1 pack,24 pack water,1,Emergency Supplies,single
7,BATT-100,BATTERIES AA 4PK,emergency supplies,AA,NaN,3M Company,6 pack,4pk aa batteries,1,Emergency Supplies,6-pack
8,BAT-AA4,AA Batteries 4-Pack,emergency supplies,AA,4.16,Kimberly-Clark,4pk,4pack aa batteries,2,Emergency Supplies,4-pack
9,BATT_AA_4PK,AA Batteries 4-Pack,emergency,AA,3.71,Anheuser-Busch,24 pack,4pack aa batteries,2,Emergency Supplies,24-pack
10,FLASH-01,FLASHLIGHT LED,emergency,Flashlight,NaN,Frito-Lay,6-pack,flashlight led,2,Emergency Supplies,6-pack
11,LED-FLASH,FLASHLIGHT LED,emergency,NaN,8.20,Frito-Lay,single,flashlight led,2,Emergency Supplies,single
12,BEER-24,Light Beer (24-pack),alcoholic beverages,NaN,9.62,Hasbro,bundle,24pack beer light,2,Alcohol,bundle
13,LTBEER24,Light Beer (24-pack),alcohol,Light,7.61,Kellogg's,bundle,24pack beer light,2,Alcohol,bundle
14,BG-MONO,Monopoly Board Game,entertainment,NaN,9.96,Kimberly-Clark,1pk,board game monopoly,3,Entertainment,single
15,MONOPOLY-01,Monopoly Board Game,entertainment,NaN,12.51,Georgia-Pacific,24-pack,board game monopoly,3,Entertainment,24-pack
16,GAME-MONO,Board Game - Monopoly,entertainment,NaN,NaN,Campbell's,1pk,board game monopoly,3,Entertainment,single
17,CARDS-01,Playing Cards,entertainment,Playing,2.45,J.M. Smucker,4pk,cards playing,2,Entertainment,4-pack
18,PLAYCARD-STD,PLAYING CARDS,entertainment,Playing,2.39,Georgia-Pacific,24-pack,cards playing,2,Entertainment,24-pack
19,STREAM-01,Roku Streaming Stick,electronics,Streaming,16.70,3M Company,12 pack,roku stick streaming,1,Electronics,12-pack
20,ROKU-STD,Streaming Device,electronics,Streaming,16.99,Anheuser-Busch,12 pack,device streaming,1,Electronics,12-pack
21,SOUP-CAN,Soup - Canned,groceries,Canned,1.23,J.M. Smucker,single,canned soup,2,Grocery,single
22,CNSOUP-01,Canned Soup,grocery,NaN,1.19,Generic Supplier,single,canned soup,2,Grocery,single
23,BREAD-WH,WHITE BREAD,grocery,Bread,1.53,Procter & Gamble,24-pack,bread white,2,Grocery,24-pack
24,WHITEBREAD,WHITE BREAD,grocery,Bread,1.12,Sara Lee,24 pack,bread white,2,Grocery,24-pack
25,PB-16,PEANUT BUTTER,grocery,Peanut,1.36,Hasbro,bundle,butter peanut,2,Grocery,bundle
26,PNUTBTR-16,Peanut Butter,grocery,Peanut,1.94,Sara Lee,1-pack,butter peanut,2,Grocery,single
27,CNDL-EM,Candles (Emergency),emergency,Candles,3.81,Frito-Lay,1 pack,candles emergency,2,Emergency Supplies,single
28,CANDLE-EMRG,Emergency Candles,emergency,Candles,3.43,Roku Inc,24pk,candles emergency,2,Emergency Supplies,24-pack
29,FAID-01,First-Aid Kit,health,First,6.90,Anheuser-Busch,4 pack,firstaid kit,1,Health,4-pack
30,FIRSTAID-KIT,First Aid Kit,health,NaN,7.85,J.M. Smucker,4 pack,aid first kit,1,Health,4-pack
31,CHRG-PORT,PORTABLE CHARGER,electronics,NaN,11.99,Georgia-Pacific,single,charger portable,1,Electronics,single
32,PORTCHARGER,Portable Phone Charger,electronics,Portable,15.03,Johnson & Johnson,12 pack,charger phone portable,1,Electronics,12-pack
33,CHIPS-VP,Variety Pack - Chips,snacks,Chips,4.03,Frito-Lay,single,chips pack variety,2,Snacks,single
34,CHIPVARIETY,Chips Variety Pack,snacks,Chips,4.11,Generic Supplier,4-pack,chips pack variety,2,Snacks,4-pack
35,PTOWEL-6,Paper Towels,household,Paper,3.85,Campbell's,4 pack,paper towels,2,Household,4-pack
36,PAPERTOWEL6,Paper Towels,household,Paper,5.09,Georgia-Pacific,12-pack,paper towels,2,Household,12-pack
37,TP-12,TOILET PAPER 12PK,household,Toilet,5.58,Campbell's,1 pack,12pk paper toilet,1,Household,single
38,TOILETPAPER12,Toilet Paper 12-Roll,household,Toilet,5.75,J.M. Smucker,24-pack,12roll paper toilet,1,Household,24-pack
39,DIAP-S3,Baby Diapers - Size 3,baby,Diapers,14.40,Procter & Gamble,single,3 baby diapers size,1,Baby Products,single
40,DIAPERS-3,DIAPERS SZ 3,baby products,Diapers,13.59,Generic Supplier,6 pack,3 diapers sz,1,Baby Products,6-pack
41,BFORM-01,Infant Formula,baby,Baby,18.87,Procter & Gamble,4-pack,formula infant,1,Baby Products,4-pack
42,BABYFORMULA,Baby Formula,baby,NaN,18.25,Sara Lee,6 pack,baby formula,1,Baby Products,6-pack
43,TARP-HD,Heavy Duty Tarp,emergency,NaN,11.90,J.M. Smucker,12 pack,duty heavy tarp,2,Emergency Supplies,12-pack
44,HDTARP-01,TARP - HEAVY DUTY,emergency,Tarp,NaN,J.M. Smucker,24pk,duty heavy tarp,2,Emergency Supplies,24-pack

In [32]:
store_loc = pd.read_csv("https://raw.githubusercontent.com/Angela-Benedict/ds2002-fa26/refs/heads/main/notebooks/walmart-hurricane-project/data/store_locations.csv")

store_loc['state'] = (
    store_loc['state']
    .str.strip()
    .str.upper()
    .str.replace(r'[^\w\s]', '', regex=True)
    .str.replace(' ', '_')
)

store_loc['state'] = (
    store_loc['state']
    .str.replace('FLORIDA', 'FL', regex=False)
    .str.replace('FLA', 'FL', regex=False)
)

store_loc['store_id'] = (
    store_loc['store_id']
    .str.strip()
    .str.upper()
    .str.replace('_', '-', regex=False)
    .str.replace(r'^(FL)(\d+)$', r'\1-\2', regex=True)
)

store_loc = store_loc.drop_duplicates()

store_loc

# We need to decide what to do with the NaNs.

,store_id,store_name,city,state,zip_code,latitude,longitude,region
0,FL-239,Walmart Supercenter Orlando,Orlando,FL,32801,28.5383,-81.3792,Central
1,FL-105,Walmart Supercenter Tampa,Tampa,FL,33602,27.9506,-82.4572,West
2,FL-330,Walmart Supercenter Miami,Miami,FL,33101,25.7617,-80.1918,South
3,FL-412,Walmart Supercenter Jacksonville,Jacksonville,FL,32099,30.3322,-81.6557,North
4,FL-287,Walmart Neighborhood Market Kissimmee,Kissimmee,FL,34741,28.2920,-81.4076,Central
5,FL-156,Walmart Supercenter Daytona Beach,Daytona Beach,FL,32114,29.2108,-81.0228,East
6,FL-501,Walmart Supercenter Fort Myers,Fort Myers,FL,33901,26.6406,-81.8723,West
7,FL-078,Walmart Supercenter Gainesville,Gainesville,FL,32601,29.6516,-82.3248,North
8,FL-619,Walmart Supercenter Tallahassee,Tallahassee,FL,32301,NaN,NaN,Panhandle
9,FL-445,Walmart Supercenter St. Petersburg,St. Petersburg,FL,33701,27.7676,-82.6403,West
10,FL-302,Walmart Supercenter Lakeland,Lakeland,FL,33801,28.0395,-81.9498,Central
11,FL-710,Walmart Supercenter Pensacola,Pensacola,FL,32501,30.4213,-87.2169,Panhandle

In [25]:
walmart_sales = pd.read_csv("https://raw.githubusercontent.com/Angela-Benedict/ds2002-fa26/refs/heads/main/notebooks/walmart-hurricane-project/data/walmart_transactions.csv")

before = len(walmart_sales)

walmart_sales_clean = walmart_sales.drop_duplicates().copy()

after = len(walmart_sales_clean)

walmart_sales_clean["store_id"] = (
    walmart_sales_clean["store_id"]
    .str.strip()
    .str.upper()
    .str.replace("_", "-", regex=False)
    .str.replace(r"^(FL)(\d+)$", r"\1-\2", regex=True)
)
walmart_sales_clean['store_id'].unique()

print(before)
print(after)

walmart_sales_clean['unit_price'] = pd.to_numeric(
    walmart_sales_clean['unit_price'].str.replace('$', '', regex=False)
)

walmart_sales_clean.dtypes

#need to clean/normalize category, product_name, sku
#need to normalize timestamp

25562
25532

transaction_id     object
store_id           object
timestamp          object
sku                object
product_name       object
category           object
quantity            int64
unit_price        float64
dtype: object

In [15]:
print(walmart_sales_clean.dtypes)

print("\nMissing values:")
print(walmart_sales_clean.isna().sum())

print("\nStore IDs:")
print(walmart_sales_clean["store_id"].unique())

print("\nNegative quantities:")
print((walmart_sales_clean["quantity"] < 0).sum())

transaction_id    object
store_id          object
timestamp         object
sku               object
product_name      object
category          object
quantity           int64
unit_price        object
dtype: object

Missing values:
transaction_id      0
store_id            0
timestamp         884
sku                 0
product_name        0
category            0
quantity            0
unit_price          0
dtype: int64

Store IDs:
['FL-710' 'FL-412' 'FL-105' 'FL-330' 'FL-302' 'FL-445' 'FL-619' ' FL-710'
 'FL-287' 'FL287' 'FL105' 'FL-239' 'FL-156' 'FL-501' 'FL-078' ' FL-330'
 ' FL-105' 'FL412' 'FL239' ' FL-287' ' FL-302' ' FL-078' ' FL-239'
 ' FL-619' 'FL330' 'FL445' ' FL-156' ' FL-412' 'FL302' 'FL078' ' FL-445'
 'FL619' 'FL710' 'FL501' ' FL-501' 'FL156']

Negative quantities:
130

In [16]:
walmart_sales_clean["store_id"] = (
    walmart_sales_clean["store_id"]
    .str.strip()
    .str.upper()
    .str.replace("_", "-", regex=False)
    .str.replace(r"^(FL)(\d+)$", r"\1-\2", regex=True)
)

print(walmart_sales_clean["store_id"].unique())

['FL-710' 'FL-412' 'FL-105' 'FL-330' 'FL-302' 'FL-445' 'FL-619' 'FL-287'
 'FL-239' 'FL-156' 'FL-501' 'FL-078']

In [17]:
walmart_sales_clean["unit_price"] = pd.to_numeric(
    walmart_sales_clean["unit_price"],
    errors="coerce"
)

print(walmart_sales_clean["unit_price"].dtype)
print("Missing prices:", walmart_sales_clean["unit_price"].isna().sum())

float64
Missing prices: 0

In [18]:
print(walmart_sales_clean["timestamp"].dropna().head(20).to_string(index=False))

2024-09-13T09:48:13
2024-09-02 20:30:20
2024-09-06 10:06:00
2024-09-30 06:29:08
2024-09-15 15:59:42
2024-09-12 10:32:34
   09/15/2024 09:26
   09/11/2024 14:47
2024-09-27 16:40:14
   09/13/2024 20:03
2024-09-26 17:22:06
09-12-2024 18:24:47
   09/09/2024 13:19
2024-09-15 08:24:01
2024-09-07 08:12:08
2024-09-29 11:49:33
2024-09-25 14:52:50
2024-09-09 07:43:43
09-10-2024 11:40:38
   09/12/2024 13:17

In [19]:
walmart_sales_clean["timestamp"] = pd.to_datetime(
    walmart_sales_clean["timestamp"].str.strip(),
    format="mixed",
    errors="coerce"
)

print(walmart_sales_clean["timestamp"].dtype)
print("Missing timestamps:", walmart_sales_clean["timestamp"].isna().sum())
print(walmart_sales_clean["timestamp"].head(10))

datetime64[ns]
Missing timestamps: 884
0   2024-09-13 09:48:13
1   2024-09-02 20:30:20
2   2024-09-06 10:06:00
3   2024-09-30 06:29:08
4   2024-09-15 15:59:42
5   2024-09-12 10:32:34
6   2024-09-15 09:26:00
7   2024-09-11 14:47:00
8   2024-09-27 16:40:14
9   2024-09-13 20:03:00
Name: timestamp, dtype: datetime64[ns]

In [23]:
negative_quantity_rows = walmart_sales_clean[
    walmart_sales_clean["quantity"] < 0
]

print("Negative quantity rows:", len(negative_quantity_rows))
print("\nNegative quantity values:")
print(negative_quantity_rows["quantity"].value_counts().sort_index())

negative_quantity_rows.head(20)

Negative quantity rows: 130

Negative quantity values:
quantity
-5     4
-4     4
-3    15
-2    53
-1    54
Name: count, dtype: int64

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
163,TXN008747,FL-078,2024-09-11 21:30:35,PAPERTOWEL6,Paper Towels,HOUSEHOLD,-2,7.91
223,TXN006255,FL-619,2024-09-09 17:10:14,DIAPERS-3,Diapers Size 3,baby,-2,25.79
563,TXN013118,FL-330,2024-09-14 11:32:05,GAME-MONO,Board Game - Monopoly,ENTERTAINMENT,-2,19.58
811,TXN022136,FL-287,2024-09-25 13:20:05,TP-12,TP 12 Pack,household,-2,9.64
1034,TXN018762,FL-619,2024-09-19 14:42:48,FAID-01,First-Aid Kit,Health,-2,14.45
1356,TXN012164,FL-619,2024-09-13 10:06:37,HDTARP-01,Heavy Duty Tarp,Emergency,-1,19.46
1453,TXN005331,FL-501,2024-09-08 08:16:33,HDTARP-01,Heavy Duty Tarp,Emergency Supplies,-1,19.00
1922,TXN002730,FL-287,2024-09-05 07:26:23,BFORM-01,Baby Formula,baby,-2,28.53
1959,TXN005909,FL-412,NaT,CHIPVARIETY,Variety Pack - Chips,SNACKS,-1,8.70
2282,TXN012306,FL-445,2024-09-13 21:07:01,FIRSTAID-KIT,First Aid Kit,Health,-2,15.61
2307,TXN017603,FL-302,2024-09-17 19:38:00,PT-12,POPTART-STRAWBERRY,Breakfast Foods,-2,3.60
2409,TXN016431,FL-501,2024-09-16 11:43:00,CNDL-EM,CANDLES - EMERGENCY,emergency,-3,5.97
2626,TXN010401,FL-445,2024-09-12 20:03:40,PORTCHARGER,PORTABLE CHARGER,Electronics,-2,24.10
2657,TXN007191,FL-501,2024-09-10 16:47:57,LTBEER24,Light Beer 24pk,Alcoholic Beverages,-3,18.56
2690,TXN016729,FL-302,2024-09-16 09:00:50,CHRG-PORT,Portable Phone Charger,Electronics,-1,24.37
3463,TXN006979,FL-287,2024-09-10 14:43:28,CANDLE-EMRG,Emergency Candles,Emergency Supplies,-2,6.07
3477,TXN003035,FL-445,2024-09-05 14:16:35,STREAM-01,Streaming Device,electronics,-1,28.67
3703,TXN010866,FL-105,2024-09-13 08:44:54,LED-FLASH,Flashlight - LED,EMERGENCY,-2,13.36
3749,TXN025271,FL-078,2024-09-30 07:07:00,STREAM-01,Roku Streaming Stick,ELECTRONICS,-1,31.02
3786,TXN000279,FL-156,2024-09-01 08:31:00,CHIPS-VP,CHIPS VARIETY PACK,snacks,-1,8.79

In [24]:
before_negative_removal = len(walmart_sales_clean)

walmart_sales_clean = walmart_sales_clean[
    walmart_sales_clean["quantity"] >= 0
].copy()

after_negative_removal = len(walmart_sales_clean)

print("Rows before:", before_negative_removal)
print("Rows after:", after_negative_removal)
print("Rows removed:", before_negative_removal - after_negative_removal)
print("Negative quantities remaining:", (walmart_sales_clean["quantity"] < 0).sum())

Rows before: 25532
Rows after: 25402
Rows removed: 130
Negative quantities remaining: 0

In [20]:
missing_timestamp_rows = walmart_sales_clean[
    walmart_sales_clean["timestamp"].isna()
]

print("Rows with missing timestamps:", len(missing_timestamp_rows))

missing_timestamp_rows.head(20)

Rows with missing timestamps: 884

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
24,TXN006442,FL-710,NaT,PAPERTOWEL6,Paper Towels,Household,1,7.82
45,TXN021737,FL-619,NaT,TP-12,TOILET PAPER 12PK,HOUSEHOLD,2,9.74
46,TXN017349,FL-501,NaT,CANDLE-EMRG,Emergency Candles,emergency,1,5.78
83,TXN019304,FL-619,NaT,BATT-100,BATTERIES AA 4PK,Emergency,1,6.56
138,TXN012731,FL-239,NaT,PT-12,POPTART-STRAWBERRY,BREAKFAST,4,3.56
146,TXN007423,FL-619,NaT,PNUTBTR-16,PEANUT BUTTER,Grocery,1,3.15
147,TXN020494,FL-619,NaT,BAT-AA4,BATTERIES AA 4PK,Emergency Supplies,5,6.32
174,TXN014455,FL-302,NaT,LTBEER24,Light Beer 24pk,ALCOHOL,2,18.17
207,TXN003954,FL-302,NaT,TARP-HD,Heavy Duty Tarp,EMERGENCY,2,20.49
225,TXN003573,FL-156,NaT,SOUP-CAN,CANNED SOUP,Groceries,3,1.98
235,TXN019042,FL-330,NaT,BFORM-01,Infant Formula,Baby,2,28.97
260,TXN005466,FL-445,NaT,SKU#459812,Pop-Tarts Strawberry,Breakfast Foods,2,3.34
302,TXN015080,FL-330,NaT,BFORM-01,Infant Formula,Baby,2,29.50
319,TXN019959,FL-445,NaT,CARDS-01,PLAYING CARDS,Entertainment,3,5.23
326,TXN016127,FL-330,NaT,ROKU-STD,Streaming Device,ELECTRONICS,1,30.38
327,TXN014928,FL-105,NaT,SOUP-CAN,CANNED SOUP,Grocery,2,1.91
366,TXN017600,FL-302,NaT,PT_STRAWBERRY,Pop-Tarts Strawberry,Breakfast,1,3.33
392,TXN011236,FL-412,NaT,GAME-MONO,Board Game - Monopoly,Entertainment,2,18.99
410,TXN015831,FL-302,NaT,CNDL-EM,Candles (Emergency),EMERGENCY,1,5.70
417,TXN017318,FL-501,NaT,BEER-24,BEER LIGHT 24PK,ALCOHOL,3,19.12

In [8]:
import sqlite3

!git clone https://github.com/Angela-Benedict/ds2002-fa26.git

connect = sqlite3.connect("ds2002-fa26/notebooks/walmart-hurricane-project/data/inventory_and_sales.db")
#I need help remembering how to use SQL lol...then I'll work on cleaning this!

fatal: destination path 'ds2002-fa26' already exists and is not an empty directory.

In [21]:
cursor = connect.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table';
""")

tables = cursor.fetchall()
print(tables)

[('daily_sales_summary',), ('inventory_levels',)]

In [22]:
daily_sales = pd.read_sql_query(
    "SELECT * FROM daily_sales_summary LIMIT 10",
    connect
)

print(daily_sales.columns.tolist())
daily_sales

['date', 'store_id', 'category', 'total_units', 'total_revenue']

         date store_id       category  total_units  total_revenue
0  2024-09-01   FL-239      Emergency         90.0        1582.55
1  2024-09-01   FL-239      Breakfast         57.0         356.99
2  2024-09-01   FL-239        Alcohol         41.0         246.65
3  2024-09-01   FL-239  Entertainment         53.0         916.56
4  2024-09-01   FL-239        Grocery         69.0         339.30
5  2024-09-01   FL-239    Electronics         71.5        1011.93
6  2024-09-01   FL-239         Snacks         43.0         493.17
7  2024-09-01   FL-239      Household         24.0         341.84
8  2024-09-01   FL-239         Health         92.0         913.83
9  2024-09-01   FL-239           Baby         52.0         551.50

### 2 — Your decision log

**TODO:** every cleaning decision, what it did, and how many rows it touched. If your teammates disagree with one of these, note the disagreement — that is useful information, not a problem to hide.

In [9]:
# TODO: print or display your decision log
# need to refresh how to use log function and start this soon.

### 3 — SKU consolidation progress

**TODO:** how many distinct SKUs did you start with, how many canonical products do you have now, and what is your largest consolidated group? Show the mapping for at least one product family. Pop-Tarts is a good one to start with.

You do not need this finished — you need it started and defensible.

In [35]:
# how many are distinct?

products_copy = products.copy()

starting_skus = products_copy["sku"].nunique()
print('how many distinct skus to start:', starting_skus)


# how many rows look like Pop-Tarts in products?

products_copy['product_name'] = products_copy['product_name'].str.lower()

matching_rows = products_copy[
    products_copy['product_name'].str.contains('pop')
]

print('rows look like poptarts:', len(matching_rows))
print(matching_rows)


# mapping for everything...

sku_mapping = {
    'PT-12': 'Pop-Tarts Strawberry',
    'SKU#459812': 'Pop-Tarts Strawberry',
    'POPTART-STRAW': 'Pop-Tarts Strawberry',
    'PT_STRAWBERRY': 'Pop-Tarts Strawberry',

    'WTR-24': 'WTR-24',
    'WATER24PK': 'WTR-24',
    'WTR_24PK': 'WTR-24',

    'BATT-100': 'BAT-AA4',
    'BAT-AA4': 'BAT-AA4',
    'BATT_AA_4PK': 'BAT-AA4',

    'FLASH-01': 'FLASH-01',
    'LED-FLASH': 'FLASH-01',

    'BEER-24': 'BEER-24',
    'LTBEER24': 'BEER-24',

    'BG-MONO': 'BG-MONO',
    'MONOPOLY-01': 'BG-MONO',
    'GAME-MONO': 'BG-MONO',

    'CARDS-01': 'CARDS-01',
    'PLAYCARD-STD': 'CARDS-01',

    'STREAM-01': 'STREAM-01',
    'ROKU-STD': 'STREAM-01',

    'SOUP-CAN': 'SOUP-CAN',
    'CNSOUP-01': 'SOUP-CAN',
}


products_copy['canonical_sku'] = (
    products_copy['sku']
    .map(sku_mapping)
    .fillna(products_copy['sku'])
)


# how many canonical?

canonical_products = products_copy['canonical_sku'].nunique()

print('how many canonical products now:', canonical_products)


# largest consolidated group?

largest_group = (
    products_copy.groupby('canonical_sku')['sku']
    .nunique()
    .sort_values(ascending=False)
)

print('largest consolidated groups:')
print(largest_group.head())


# check the mapping

display(
    products_copy[
        products_copy['sku'].isin(sku_mapping.keys())
    ][['sku', 'product_name', 'canonical_sku']]
)

how many distinct skus to start: 45
rows look like poptarts: 4
             sku          product_name         category subcategory  \
0          PT-12  pop-tarts strawberry  Breakfast Foods         NaN
1     SKU#459812   strawberry pop-tart        Breakfast   Pop-Tarts
2  POPTART-STRAW  pop-tarts strawberry        Breakfast         NaN
3  PT_STRAWBERRY  pop-tarts strawberry        breakfast   Pop-Tarts

   unit_cost           supplier package_size      normalized_name
0       1.93  Johnson & Johnson       4-pack  poptarts strawberry
1       2.26           Roku Inc          4pk  poptarts strawberry
2       2.11           Sara Lee       6 pack  poptarts strawberry
3        NaN         Campbell's       4 pack  poptarts strawberry
how many canonical products now: 31
largest consolidated groups:
canonical_sku
Pop-Tarts Strawberry    4
BG-MONO                 3
BAT-AA4                 3
WTR-24                  3
FLASH-01                2
Name: sku, dtype: int64

              sku           product_name         canonical_sku
0           PT-12   pop-tarts strawberry  Pop-Tarts Strawberry
1      SKU#459812    strawberry pop-tart  Pop-Tarts Strawberry
2   POPTART-STRAW   pop-tarts strawberry  Pop-Tarts Strawberry
3   PT_STRAWBERRY   pop-tarts strawberry  Pop-Tarts Strawberry
4          WTR-24     bottled water 24pk                WTR-24
5       WATER24PK  bottled water 24-pack                WTR-24
6        WTR_24PK        water - 24 pack                WTR-24
7        BATT-100       batteries aa 4pk               BAT-AA4
8         BAT-AA4    aa batteries 4-pack               BAT-AA4
9     BATT_AA_4PK    aa batteries 4-pack               BAT-AA4
10       FLASH-01         flashlight led              FLASH-01
11      LED-FLASH         flashlight led              FLASH-01
12        BEER-24   light beer (24-pack)               BEER-24
13       LTBEER24   light beer (24-pack)               BEER-24
14        BG-MONO    monopoly board game               BG-MONO
15    MONOPOLY-01    monopoly board game               BG-MONO
16      GAME-MONO  board game - monopoly               BG-MONO
17       CARDS-01          playing cards              CARDS-01
18   PLAYCARD-STD          playing cards              CARDS-01
19      STREAM-01   roku streaming stick             STREAM-01
20       ROKU-STD       streaming device             STREAM-01
21       SOUP-CAN          soup - canned              SOUP-CAN
22      CNSOUP-01            canned soup              SOUP-CAN

### 4 — One working weather API call

**TODO:** show the call and the parsed DataFrame. It must include the retry logic and a `source` column. Say which timezone the weather timestamps are in and how you will line them up with the sales timestamps. If it is not working, paste the actual error and what you have tried.

In [11]:
# not started yet

### 5 — One chart

**TODO:** daily order volume across your date range. It does not need to be presentation quality yet, but it does need labeled axes and a title.

Look at it before you submit. Does the shape make sense? An early chart is the fastest way to catch a cleaning bug — if your daily volume has a day at zero or a day at ten times everything else, that is usually your pipeline, not the hurricane.

In [12]:
# not started yet

### 6 — Self-check

Fill in what you have and leave the rest. **The required items are the team setup and the charter.** Everything else is progress we want to see, not a pass or fail. The checks are shape checks; they cannot verify your analysis is right, only that you have gotten far enough to have one.

In [13]:
required = {
    'team_setup_complete': check_team(team_setup, quiet=True),   # from the team setup section
    'charter_committed': True,         # TODO: True once CHARTER.md shows in the git log above
}

progress = {
    'rows_after_cleaning': len(walmart_sales_clean),        # an integer
    'decisions_logged': None,           # how many entries in your log
    'canonical_products': None,         # distinct products after consolidation
    'weather_api_rows': None,           # rows returned by your API call
    'notebook_runs_clean': False,       # True after Restart and Run All
}

def is_done(value):
    return not (value is None or value is False
                or (isinstance(value, str) and value.startswith('TODO')))

def check(required, progress):
    print('REQUIRED')
    for label, value in required.items():
        print('  PASS' if is_done(value) else '  FAIL', '-', label, '=', value)
    print('PROGRESS (fill in what you have)')
    for label, value in progress.items():
        print('  done' if is_done(value) else '  not yet', '-', label, '=', value)
    ok = all(is_done(v) for v in required.values())
    print()
    print('required items complete:', ok)
    print('progress items done:', sum(is_done(v) for v in progress.values()), 'of', len(progress))
    return ok

check(required, progress)

REQUIRED
  PASS - team_setup_complete = True
  PASS - charter_committed = True
PROGRESS (fill in what you have)
  done - rows_after_cleaning = 25532
  not yet - decisions_logged = None
  not yet - canonical_products = None
  not yet - weather_api_rows = None
  not yet - notebook_runs_clean = False

required items complete: True
progress items done: 1 of 5

True

### 7 — Risk and plan

Two questions, answered concretely.

**a)** What is the single most likely thing to go wrong in the next two weeks? Name a specific technical or team problem, not "running out of time."

**b)** What are you doing about it this week? Name who is doing it and by when.

**Biggest risk:** Miscommunication between team members that causes us to make a mistake in data cleaning or undo each other's work.

**Plan, with an owner and a date:** This week to ensure we are not undoing each other's work, we made Angela the owner and lead. This means she is turning everything in and the team lets her know if we are working on something so there is no rewriting.

### 8 — Where each question stands

**TODO:** mark each of the five questions. These owners must match the question owners table in your charter. Be honest — this is the section I read first.

| Question | Status | Who owns it |
|---|---|---|
| Q1 demand surge | not started / in progress / draft answer | _Angela_ |
| Q2 SKU consolidation | in progress | Aubin |
| Q3 weather correlation | not started | Noor |
| Q4 store and geography | not started | Nico |
| Q5 signal or artifact | _not started_ | _Angela_ |

At the end of week 1, "not started" on Q4 and Q5 is expected. "Not started" on all five means come find me on Monday.